language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

sudo: false

install:
  - pip install nose coverage coveralls
  - pip install pytest>=2.7.3 --upgrade
  - pip install -r requirements.txt

script:
  - nosetests -v --with-coverage --cover-package=javaobj tests

after_success:
  - coveralls
