language: python
python: 3.5

env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=pypy
  - TOX_ENV=pypy3

install:
  - pip install tox
  - pip install coverage
  - pip install coveralls
  - pip install pytest>=2.7.3 --upgrade

script:
  - tox -e $TOX_ENV

after_success:
  - coverage combine
  - coveralls
